repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Run ruff check before commit
        entry: uv run ruff check
        args: [ --fix ]
        language: system
        pass_filenames: false

      - id: ruff-format
        name: Run ruff format before commit
        entry: uv run ruff format
        language: system
        pass_filenames: false

      - id: mypy
        name: Run mypy before commit
        entry: uv run mypy
        language: system
        types: [ python ]
        pass_filenames: false

      - id: pylint
        name: Run pylint before commit
        entry: uv run pylint
        language: system
        types: [python]
        pass_filenames: true

      - id: pytest
        name: Run pytest before commit
        entry: uv run pytest --cov=. --cov-report term-missing:skip-covered --cov-fail-under=100
        language: system
        types: [ python ]
        pass_filenames: false

      - id: mkdocs
        name: Run mkdocs before commit
        entry: uv run mkdocs build
        language: system
        pass_filenames: false