[tool.poetry]
authors = ["Christian Sonder <christian.sonder@unisg.ch>", "Bastian Politycki <bastian.politycki@unisg.ch>"]
description = "A customizable XML formatter based on Python's minidom."
name = "xmldomformatter"
readme = "README.md"
version = "0.1.0"

[tool.poetry.scripts]
xdf = "xmldomformatter.cli:main"

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
mypy = "^1.5.0"
pytest = "^7.4.0"
ruff = "^0.0.284"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
